theme: jekyll-theme-minimal
title: [CHELSY MENA]
description: [Check out my latest Data Science projects!]
logo: [https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn.dribbble.com%2Fusers%2F155459%2Fscreenshots%2F3343081%2Fcm_monogram_1x.png&f=1&nofb=1]
